### ISSUE TITLE
OC can't find  relative file  when import

### ISSUE THREAD

**Issue by xRuby** [NordicSemiconductor/IOS-DFU-Library#34]
I  do  setup   two,  and set Embedded Content Contains Swift Code  to  Yes, but can't  find DUF relative header file.  why

**Comment by LtkDev** [comment]
@xRuby 
I'm import the DFULibrary as source code and do all setup, but my project still can't use library.
What header file should import ?  I can't call DFUServiceDelegate, DFUServiceInitator...etc.
What should I do to start it ?  Is something I miss ?

**Comment by xRuby** [comment]
@LtkDev try to build the DFULibrary ，and last i use pod the code，advice you too.

**Comment by mostafaberg** [comment]
@LtkDev if your issue isn't resolved open up a new issue and we can help. there are no header files in Swift
