### ISSUE TITLE
DFUFirmware  is nil， why ？ by setup two or three，selectedFileUrl is exist.

### ISSUE THREAD

**Issue by xRuby** [NordicSemiconductor/IOS-DFU-Library#35]
DFUFirmware* selectedFirmware = [[DFUFirmware alloc] initWithUrlToZipFile:selectedFileUrl];

selectedFirmware is nil, why ?    I do it by setup two  and three.

the file can upgrade by demo nRF-Toolbox,  file type is zip.

**Comment by mostafaberg** [comment]
Hi xRuby!, Is the zip file copied over in the build steps ? might be just lying there in Xcode but is not copied to your device when you build, can you print out the output of `selectedFileUrl` ?

**Comment by xRuby** [comment]
Yes, it is copied over in the build steps, and can get size of the file, but why the selectedFirmware is nil too.  I think the method is not do as before, but I can't debug it,

**Comment by mostafaberg** [comment]
Can you log the value of `selectedFileUrl` and paste it here ?

**Comment by xRuby** [comment]
Hi,  thank you very much, I do it  by  first method (pod 'iOSDFULibrary'),  it can upgrade.  i will try to do it by  second and third method later. thank your answer.

**Comment by mostafaberg** [comment]
Changing the method won't fix the problem, it's the same library, just different installation methods.

I can't help without getting any more details from you I'm afraid, however it seems like an issue with your app and not the library since it works when we test it

**Comment by xRuby** [comment]
Hi, I do it  by second method,  add iOSDFULibrary.framwork  to my project, and it is exist in link binary. but when i  '#import "iOSDFULibrary-swift.h"', the error is file not found. when i '#import <iOSDFULibrary/iOSDFULibrary-Swift.h>' , the selectedFirmware is nil.

**Comment by xRuby** [comment]
when i '#import <iOSDFULibrary/iOSDFULibrary-Swift.h>' , the selectedFirmware is nil.

**Comment by mostafaberg** [comment]
I'm not asking about the `selectedFirmware`, I'm asking about `selectedFileUrl` please give me that value so I can help you. as I said earlier, the problem is not in the library so installing it in a different way won't help

**Comment by xRuby** [comment]
selectedFileUrl is '/var/containers/Bundle/Application/A43CAB95-636A-4F37-B05A-FEE2D2EC0D8D/BodyPlus.app/firmwares/nrf_0005_160810.zip' , and i can get size of the file by the path.

**Comment by mostafaberg** [comment]
perfect, does the library show anything special in the logs ?

**Comment by xRuby** [comment]
there is nothing...

**Comment by mostafaberg** [comment]
That's very strange, the our zip code never returns nil without throwing an exception, what version of Xcode are you using and what kind of device is this happening on ?, also do you see any other logs than from the library at all ?

**Comment by xRuby** [comment]
is use `#import <iOSDFULibrary/iOSDFULibrary-Swift.h>` ?   but use `#import "iOSDFULibrary-swift.h"`, the error is the file not found.

xcode: 7.3    device: 6p, 9.3.2

**Comment by mostafaberg** [comment]
I would recommend going back to cocoapods to avoid that kind of confusion. I'm not sure which one you are using but the general consensus is `#import target_name-Swift.h`, if it's not found then you need to create the file, again, it's too much of a hassle, just use cocoapods package instead

does your log show anything at all ? if you `NSLog()` something can you see it ? i'm suspecting your logs are hidden for some reason. if you have a screenshot of your Xcode window i might be able to see that for you

**Comment by xRuby** [comment]
Another problem, I pod it to upgrade it,  the framework don't do disconnected in DFU and no error delegate do, before upload completed.

**Comment by mostafaberg** [comment]
So from what I understand, it starts uploading when you use the cocoapods package ?
On Aug 10, 2016 15:55, xRuby <notifications@github.com> wrote:Another problem, I pod it to upgrade it,  the framework don't do disconnected in DFU and no error delegate do, before upload completed.

**Comment by mostafaberg** [comment]
hi @xRuby did you resolve the problem ?
