### ISSUE TITLE
i'm trying to send next packet but callback return always error 

### ISSUE THREAD

**Issue by cheignon** [NordicSemiconductor/IOS-DFU-Library#38]
in  function  sendNext(number:UInt16, packetsOf firmware:DFUFirmware, andReportProgressTo progressDelegate:DFUProgressDelegate?) 

the sending speed is not managed .

so i replace 
 peripheral.writeValue(packet, forCharacteristic: self.characteristic, type: CBCharacteristicWriteType.WithoutResponse)

by 

```
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(0.1 * dispatch_time_second * Double(NSEC_PER_SEC))), dispatch_get_main_queue(), {
    peripheral.writeValue(packet, forCharacteristic: self.characteristic, type: CBCharacteristicWriteType.WithoutResponse)
});
```

**Comment by mostafaberg** [comment]
This is quite wrong and will not work, what are you trying to accomplish ?

**Comment by cheignon** [comment]
For me it's works but if you are a best solution, I'm ok for use it.

**Comment by mostafaberg** [comment]
Can you tell me what the problem you had was that made you need that change ? I can help further if i know what the issue is

**Comment by cheignon** [comment]
When i try to update the firmware my Bluetooth board disconnect automatically after 6 packet. So i think the sending speed it's too high.


Cordialement,
Cheignon Dorian

**Comment by cheignon** [comment]
Okay i try with notification = 1

Cordialement,
Cheignon Dorian

**Comment by mostafaberg** [comment]
Closing this since it's too old and now the library is obsolete, please use the one in the link and repost any issues there
https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library
