### ISSUE TITLE
Carthage can't support the tag name like '1.0.8(18)'

### ISSUE THREAD

**Issue by calvingit** [NordicSemiconductor/IOS-DFU-Library#41]
Using `carthage update`,  just fetch the "1.0.6" version of the repo. 
rename the tag with only version，not with the build number.

**Comment by mostafaberg** [comment]
Ouch, thanks for the tip!, will fix that on the upcoming release!

**Comment by mostafaberg** [comment]
[Version 2.0](https://github.com/NordicSemiconductor/IOS-DFU-Library) is out in the Cocoapods repo, it's tagged as `2.0` without build numbers so it should work for you if you use it, I would recommend building it there, we are going to also include an `SPM` soon on the cocoapods repo
