### ISSUE TITLE
iOS 10 Device is in invalid state error

### ISSUE THREAD

**Issue by aparesidam** [NordicSemiconductor/IOS-DFU-Library#43]
Hi,

On iOS 10 while processing DFU I receive error RemoteInvalidState in didErrorOccur method with description "Device is in invalid state". This error occurs just after starting the DFU, after receiving 1% progress. Is anyone reproducing this issue?

Thanks in advance

**Comment by jovirus** [comment]
Hi,
which version of DFU are you using? We have latest nRF Toolbox, did you check on that?

**Comment by aparesidam** [comment]
Hi,

Thank you for your comment. I used version 1.0.0 and now I updated the library to the latest one which is 1.0.8 for now and DFU successfully worked. Thanks!
