### ISSUE TITLE
Pod iOSDFULibrary (1.0.12) not compatible with Xcode7/Swift2.2

### ISSUE THREAD

**Issue by lha-ryq** [NordicSemiconductor/IOS-DFU-Library#46]
Hi,

I have a problem with using your library in Xcode7/Swift2.2 project with CocoaPods. It is related with Zip dependency that you are using in your code. Today new Zip version 0.5/0.6 was released that supports Swift3. This means that now I am not able to compile my project.

I saw that you are using in podspec file:
```
"dependencies": {
    "Zip": [
      "~> 0.3"
    ]
  }
```

Would be great if you could set direct Zip version in your podspec. Zip 0.4.3 looks like the last compatible version.

**Comment by mostafaberg** [comment]
The issue was that the Zip library was not Swift 3.0 compatible at the time, there is a branch out there already that we contributed to to speed up the process, we will fully test and re-release a proper version this coming working week! sorry for the delays!

**Comment by lha-ryq** [comment]
Thanks for the info. Great to hear that you want to fix it in next week.

**Comment by mostafaberg** [comment]
I have misread your title and thought you were talking about Xcode8.
Is there any reason you're using Xcode 7 ? 

We have just released a [iOSDFULib 2.0](https://cocoapods.org/pods/iOSDFULibrary) and from this point forward we will only support Xcode 8 and Swift 3.0.

In your case you have to either update to Xcode8/Swift3 or simply stick to version `1.0.12` of the library, the Zip library also will not support any versions of Swift below 3.0 which I would personally recommend (Swift2.3 is just a transitional version and will be deprecated soon anyway, and Swift 3.0 will eventually be deprecated as soon as Swift 4.0 is out)

so I would personally recommend that you Update to Swift 3.0 and iOSDFULibrary 2.0 as soon as you can to avoid the hassle in the near future.
