### ISSUE TITLE
'iOSDFULibrary-Swift.h' file not found

### ISSUE THREAD

**Issue by weweco123** [NordicSemiconductor/IOS-DFU-Library#464]
Code: #import <iOSDFULibrary-Swift.h>
I used oc and swift to compile, and there was a problem:'iOSDFULibrary-Swift.h' file not found.

Platform: xcode13.0
Use cocopod: pod'iOSDFULibrary'

No problem on the basis of xcode12.

help.

**Comment by DavidAPears** [comment]
Any idea's on this - I seem to have hit the same issue. :/

**Comment by agussaputrasijabat** [comment]
Same issue here :)

**Comment by Nidcoco** [comment]
if using the library in OC project，don’t #import <iOSDFULibrary-Swift.h> ，but @import iOSDFULibrary;

**Comment by philips77** [comment]
Hope that worked for you! We stopped testing the project in OC some time ago. If you still experience issues, please create a new issue.
