### ISSUE TITLE
When will you support swift 3.0

### ISSUE THREAD

**Issue by trilliwon** [NordicSemiconductor/IOS-DFU-Library#47]

**Comment by mostafaberg** [comment]
It's currently in progress and will be ready this week!

**Comment by huguesbr** [comment]
isn't dup of https://github.com/NordicSemiconductor/IOS-DFU-Library/issues/30, should be close?

**Comment by mostafaberg** [comment]
Sure thing, seems like I forgot to close that , thanks 👍
