### ISSUE TITLE
Xcode 13.3 and 13.4 Compliation Error

### ISSUE THREAD

**Issue by mldesanctis-cgi** [NordicSemiconductor/IOS-DFU-Library#475]
**Information**
Cannot compile release 4.11.1 in Xcode 13.3/13.4. Receive compilation error 
`Module compiled with Swift 5.5.2 cannot be imported by the Swift 5.6/5.6.1 compiler: Build/Products/Debug-iphonesimulator/iOSDFULibrary.framework/Modules/iOSDFULibrary.swiftmodule/x86_64-apple-ios-simulator.swiftmodule`

**Comment by philips77** [comment]
This might have been fixed with 4.12.0 release.
