### ISSUE TITLE
Add CBCentralManager options to DFUServiceInitiator initializer

### ISSUE THREAD

**Issue by mateusforgi** [NordicSemiconductor/IOS-DFU-Library#476]
**DFU Bootloader version (please complete the following information):**
 - Library version: 4.10.4

**Device information (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 15.4.1

**Describe the bug**
The DFUServiceInitiator initializer does not offer an option to pass `CBCentralManagerOptions` (unless we use the deprecated one), so we cannot use [`CBCentralManagerOptionShowPowerAlertKey`](https://developer.apple.com/documentation/corebluetooth/cbcentralmanageroptionshowpoweralertkey) set to false resulting in the user getting a modal asking permission for bluetooth connections.

**Comment by mateusforgi** [comment]
@philips77 are you guys planning a new release soon?

**Comment by philips77** [comment]
I'll try today.
