### ISSUE TITLE
Difference between DfuViewModel and DFUViewController and use of urlToZipFile, DFUFirmwareProvider

### ISSUE THREAD

**Issue by xaviergspintly** [NordicSemiconductor/IOS-DFU-Library#507]
I have a question which may have a very simple answer.
I am trying to replicate the example code in a basic project of mine, but, I see that there is repetition of the core logic that I have to use in the files DfuViewModel and DFUViewController.
Which of these files should I actually reference? I feel it is DFUViewController, but please can you explain me the use of both these files in your example project.
I couldn't find any linking between them and in what context are they used separately if so.

Secondly, wanted to know if zip firmware has to be downloaded locally before giving zip url to library?
Or is it possible to just give the online HTTPS url and the library will download it and upload to device?
Like in the below, can I wive the HTTPS URL:
`let selectedFirmware = try DFUFirmware(urlToZipFile: url)`
Because I can see `FileSectionView.swift` and it looks like download using `URLSession` has to be done.

Also wanted to know how the DFUFirmwareProvider is used since it is not mentioned in the documentation at:
https://github.com/NordicSemiconductor/IOS-DFU-Library/blob/main/documentation.md
The DFUFirmwareProvider implementation seems important for getting it working but the docs don't explain its use.

**Comment by xaviergspintly** [comment]
Ha, OK! So, is DFUFirmwareProvider used to only load a test set of firmware? Or is it really part of the library? Can it be just replaced with my firmware zip?

**Comment by philips77** [comment]
Hello,
You need to create a `DFUFrimware` instance and pass it to the `DFUServiceInitiator`.
The `DFUFirmwareProvider` is just a class used in the test app to provide a firmware for each test, that's why it's not documented.

And yes, you need to download the file locally, I believe.

**Comment by xaviergspintly** [comment]
@philips77 I got that part of DFUFrimware and DFUServiceInitiator before even asking the question. But why are there 2 similar implementations in DfuViewModel and DFUViewController. What is the difference between these two files which have similar code? And which should I pick to refer?

**Comment by philips77** [comment]
@sylwester-zielinski could you help? I don't know the details.

**Comment by sylwester-zielinski** [comment]
@xaviergspintly I can't find the class DFUViewController. Can you provide a link to it?

**Comment by xaviergspintly** [comment]
https://github.com/NordicSemiconductor/IOS-DFU-Library/blob/main/Example/iOSDFULibrary/View%20Controllers/DFUViewController.swift

**Comment by philips77** [comment]
The app in *Example* folder is a test app for DFU. Don't look there. It's an old app, mainly for internal use.
The app released on AppStore is in *App* folder.
