### ISSUE TITLE
What file should import?

### ISSUE THREAD

**Issue by LtkDev** [NordicSemiconductor/IOS-DFU-Library#52]
I'm import the DFULibrary as source code and do all setup, but my project still can't use library.
I can't call DFUServiceDelegate, DFUServiceInitator...etc.
What should I do to start it ? Is something I miss ?

**Comment by mostafaberg** [comment]
Well it surely seems to be a wrong configuration somewhere, We don't recommend importing the source code directly like that, it's better to use Cocoapods, if you can't use cocoapods we do support carthage, this will basically give you a precompiled `.framework` file to import into your project


try going to our [cocoapods page](https://cocoapods.org/pods/iOSDFULibrary) and see the Carthage instructions

**Comment by LtkDev** [comment]
@mostafaberg  Thanks a lot.
Hi, I have build iOSDFULibrary.framework by Carthage. And set 
  1.Embed Swift Standard Libraries
  2.New Run Script Phase
  3.New Copy Files Phrase 
  4.Embedded Binaries
  5.Linked Frameworks and Libaries

I got the build failed. Is something I miss?

**Comment by mostafaberg** [comment]
I'll need more info on that, what's failing, any messages ?

**Comment by LtkDev** [comment]
![2016-10-07 5 12 59](https://cloud.githubusercontent.com/assets/21099730/19185659/395f7bc6-8cb5-11e6-9833-6ad743456a7b.png)

**Comment by mostafaberg** [comment]
In the top of that class that's throwing the errors can you try to import the generated `ObjC` Header
should be called `iOSDFULibrary-swift.h` and see if that helps, if not you can checkout [this guide](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html) by apple on how to use `Swift` code in `ObjC`

let me know if that helps

**Comment by LtkDev** [comment]
@mostafaberg 
It's build succeeded after add this line.
    #import <iOSDFULibrary/iOSDFULibrary-swift.h>
But failed to run as following,
dyld: Library not loaded: @rpath/**Zip.framework/Zip**
  Referenced from: /private/var/mobile/Containers/Bundle/Application/CB4AE11F-EFE1-4379-9AFE-D10781014257/HealthCube.app/Frameworks/iOSDFULibrary.framework/iOSDFULibrary
  Reason: image not found

I'm use clean project to do all step.

**Comment by mostafaberg** [comment]
Oh, That would probably be a mistake on our side ! so sorry about that

Can you try adding the Zip library to your cartfile ?
`github "marmelroy/Zip"`

and copy it over to your project same way you did with our library, this should hopefully set things up for you

**Comment by Joyce306** [comment]
I have a question that my firmware program is update by about 15% ,than while it shows  a Alert (Upload aborted or Operation not permitted). Could you  tell me  the reason  or how  I can find  the  reason? Thank you very much!  My English is poor and I hope My question is clear. @mostafaberg

**Comment by LtkDev** [comment]
@mostafaberg 
Thank you so much! It's worked.

**Comment by Joyce306** [comment]
@mostafaberg   I've already done it.  hahaha, I'm  so  happy . Our hardware engineers made a mistake. Now，I got it . 23333

**Comment by mostafaberg** [comment]
Great work guys !, i'll have a ticket to relsove this issue within the library so you won't have to deal with dependencies like that !
