### ISSUE TITLE
New release needed with ZipFoundation 0.9.18 to fix vulnerability

### ISSUE THREAD

**Issue by jdanthinne** [NordicSemiconductor/IOS-DFU-Library#529]
Now that ZipFoundation 0.9.18 is available through Cocoapods (https://github.com/weichsel/ZIPFoundation/issues/300#issuecomment-1956078844), can you make a new release with an updated .podspec (I saw the Package.swift is already updated, but not released yet), please?

**Comment by philips77** [comment]
Sure!
