### ISSUE TITLE
when I used , some object release , please help me fix this bug

### ISSUE THREAD

**Issue by yaoquanfeng123** [NordicSemiconductor/IOS-DFU-Library#53]
-[iOSDFULibrary.DFUExecutor peripheral:didDiscoverServices:]: message sent to deallocated instance 0x15e1cc4b0

**Comment by mostafaberg** [comment]
I would recommend using our [new library first](https://github.com/NordicSemiconductor/IOS-PODS-DFU-Library/)

if you try to enable zombie objects, then when it crashes try to `po 0x15e1cc4b0` or whatever address it is, then see what class type it is

then hold a reference to that object in the class that's handling DFU process

a code snippet would help too if you have any.

but both cases you really should be using the Pods version of the library

**Comment by yaoquanfeng123** [comment]
thank you
