### ISSUE TITLE
Module 'iOSDFULibrary' not found

### ISSUE THREAD

**Issue by DockLle** [NordicSemiconductor/IOS-DFU-Library#538]
install by cocoapods
version 4.15.3 ：
<img width="1086" alt="截屏2024-09-14 11 32 05" src="https://github.com/user-attachments/assets/0b39f3fc-d098-4958-8b99-0696ae163fa0">
version 4.13.0 :normal

**Comment by philips77** [comment]
Have a look at the migration guide for 4.14+:
https://github.com/NordicSemiconductor/IOS-DFU-Library/releases/tag/4.14.0
