### ISSUE TITLE
Will there be new Cocoapod releases?

### ISSUE THREAD

**Issue by aetrocks** [NordicSemiconductor/IOS-DFU-Library#541]
Hello everyone,

will there be a newer Release for the DFU Library as Cocoapod?

We are currently using Kotlin Multiplatform to combine the iOS and android nordic dfu libraries as one multiplatform Firmware library for our devices.

The problem is that I need them as cocoa pods to use them in KMM.

I saw that you are releasing newer versions as SPM but the cocoapod is still version 4.13.0, are there any plans to release them as cocoa pods too?

Thanks in advance and best regards
Simon

**Comment by philips77** [comment]
OMG, this should be on CocoaPods as well. Let me check...

**Comment by philips77** [comment]
OMG, this should be on CocoaPods as well. Let me check...

**Comment by philips77** [comment]
The latest version on CocoaPods is 4.15.3:
https://github.com/CocoaPods/Specs/blob/master/Specs/0/e/5/iOSDFULibrary/4.15.3/iOSDFULibrary.podspec.json

**Comment by philips77** [comment]
I don't know why the search isn't showing it, but it should be accessible. In 4.14 we renamed the module to `NordicDFU` (see [4.14.0](https://github.com/NordicSemiconductor/IOS-DFU-Library/releases/tag/4.14.0)), perhaps that is what causes the trouble?
