### ISSUE TITLE
Will there be a complete rename to NordicDFU?

### ISSUE THREAD

**Issue by aetrocks** [NordicSemiconductor/IOS-DFU-Library#544]
Hello everyone, 

short question: 
Will there be a complete rename to NordicDFU or is it planned to use the iOSDFULibrary/NordicDFU mix naming?

Best Regards

Simon

**Comment by philips77** [comment]
The only reason why it's still called _iOSDFULibrary_ is for compatibility reasons. On SPM it's already [_NordicDFU_](https://github.com/NordicSemiconductor/IOS-DFU-Library/blob/2db0d4f26a4812dfb7553e50e2a10f53f7b95114/Package.swift#L9) and the module name in CocoaPods is also [_NordicDFU_](https://github.com/NordicSemiconductor/IOS-DFU-Library/blob/2db0d4f26a4812dfb7553e50e2a10f53f7b95114/iOSDFULibrary.podspec#L3).

If we'd change on CocoaPods, it would be a new repo without the "previous versions".
Any reason you wish it to be renamed other than keeping clean?

**Comment by aetrocks** [comment]
At the moment I need to wrap iOS and Android Nordic DFU Libs in Kotlin Multiplatform to use it in a Kotlin Multiplatform Lib that offers DFU options. 
With 4.13 and kotlin 1.9.23 and Java 17, no kotlin-lib for arm64 on iOSDFULibrary is built. 
If I update kotlin to 2.0.x and pull up Java, it's weirdly build (not sure why, still searching).
The lib is used in Unity and Maui, so Kotlin 2.0 is a bit too new for those. 
Going up to Java 21 ist the next dependency problem. 
If I go higher in version of iOSDFULibrary I get into the next problem, that kmm runs into multiple errors when adding the pod because it cannot find the iOSDFULibrary even if I specify that its module name is NordicDFU. 

So multiple Problems at the Firmware Update Side on our Project, at the moment we completely shutdown this option for our product until I get this fixed somehow. 
If there would be a new Repo for cocoa pods with the name NordicDFU I could at least go to a higher version and concentrate on the multiple other errors. 

I know those are problems that are not considered because no kmm support and focus is on cocoapods/SPM users in native apps. But I can't get around getting this to work. `:) 

Maybe, it is like in earlier issues I wrote, that the problem is on my side or there are other things I dont see at the moment to fix those problems, but yeah I dont see how this could be fixed at the moment.

Thanks a lot and sorry for the long text

**Comment by philips77** [comment]
Let me tel you my big[^1] plans. We're working on a new [Kotlin BLE library, version 2.0](https://github.com/NordicSemiconductor/Kotlin-BLE-Library/tree/version/2.0) which is supposed to be kmm at some point. Right now I write bunch of kotlin-only modules with logic and android implementation modules, which should change to kmm later, when time allows.

Based on these, we may migrate most libraries to this library as transport, allowing all to be in kmm (if not supported by us, at least easy to implement by others). I don't have much experience with kmm and don't know how easy it's to include such library in Swift projects, so we could deprecate existing Swift code in favor of Kotlin. Anyway, that's years ahead.

If it helps you, I can release DFU as NordicDFU for now.

[^1]: Long term :(

**Comment by aetrocks** [comment]
In terms of implementation and so on for swift, kmm is just the "builder" in the end kmm creates a .framework or spm package for you to deploy but additionally you can deploy it as maven repo and other kmm libs or android apps can import it very easily too, but with the benefit of just having to maintain one codebase. 

Its nice to hear that in the future I can maybe just use the nordic kmm lib and not need to wrap all libs together myself :D 
At the moment I wrap android ble, custom ble corebluetooth iOS and nordic dfu android and nordic dfu iOS just to use it in kmm. 

if you could publish it in parallel with the new name just for the latest version it would be really great. :)

**Comment by philips77** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  NordicDFU (4.16.0) successfully published
 📅  December 12th, 22:35
 🌎  https://cocoapods.org/pods/NordicDFU
 👍  Tell your friends!
--------------------------------------------------------------------------------
